### ISSUE TITLE
I cannot run the bot

### ISSUE THREAD

**Issue by SaSiNO97** [woosal1337/Chegg-Discord-BOT#4]
I can't run the bot. 
I installed python3 and two modules (discord and apscheduler). 
```
root@eu2:/opt/Chegg-Discord-BOT-main/Chegg-Discord-BOT-INIT-2# python3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 1, in <module>
    from lib.bot import bot
  File "/home/users/temp/Chegg-Discord-BOT-main/Chegg-Discord-BOT-INIT-2/lib/bot/__init__.py", line 6, in <module>
    from ..db import db
  File "/home/users/temp/Chegg-Discord-BOT-main/Chegg-Discord-BOT-INIT-2/lib/db/__init__.py", line 1, in <module>
    from . import db
  File "/home/users/temp/Chegg-Discord-BOT-main/Chegg-Discord-BOT-INIT-2/lib/db/db.py", line 39
    if (fetch := cur.fetchone() is not None):
              ^
SyntaxError: invalid syntax
```

Any help appreciated :)

**Comment by eldensavage** [comment]
Hello. Our server is down due to server costs. We'll fix it in 2 days.
Thanks for reaching out.

best,
Eldaniz

**Comment by woosal1337** [comment]
Make sure you are using Python 3.9+.  `:=` is Python 3.9 specific feature.

**Comment by SaSiNO97** [comment]
> Make sure you are using Python 3.9+. `:=` is Python 3.9 specific feature.

Thank you very much ♥, it worked with Python 3.9, however I'm now getting different errors (after installing all the required dependencies...)
I'll open a new issue for that
