### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by SaSiNO97** [woosal1337/Chegg-Discord-BOT#5]
Hello,
I installed Python 3.9 and all the requirements using pipreqs (as in this [stackoverflow post](https://stackoverflow.com/questions/46419607/how-to-automatically-install-required-packages-from-a-python-script-as-necessary)'s second answer), however there's one dependency that was not resolved, which is the "Crypto" module.
How can I get this module?

```
# python3.9 launcher.py

Committing...
Running Setup...
fun
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/cogs/fun.py", line 5, in <module>
    from lib.bot.firebaseauth import addUser, getUser, getUserMail, updateMail, deleteUser
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/firebaseauth.py", line 1, in <module>
    from firebase import firebase
  File "/usr/local/lib/python3.9/dist-packages/firebase/__init__.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/temp/Chegg-Discord-BOT-main/launcher.py", line 5, in <module>
    bot.run(VERSION)
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 54, in run
    self.setup()
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 45, in setup
    self.load_extension(f"lib.cogs.{cog}")
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'lib.cogs.fun' raised an error: ModuleNotFoundError: No module named 'Crypto'
```

**Comment by woosal1337** [comment]
`pip install python-firebase`

**Comment by Sonjayt** [comment]
Hi there! Am facing the same issues eventhough I have already used pip install python-firebase but the same error still pops up. Any idea?

**Comment by SaSiNO97** [comment]
> Hi there! Am facing the same issues eventhough I have already used pip install python-firebase but the same error still pops up. Any idea?

I was using Python 3.9 on Linux, so I ran the command as `python3.9 -m pip install python-firebase` however I kept getting error after error so I gave up

**Comment by woosal1337** [comment]
This project has ended.
