### ISSUE TITLE
Error within the firebase lib. Do I need a specific version of it?

### ISSUE THREAD

**Issue by SaSiNO97** [woosal1337/Chegg-Discord-BOT#6]
Hello, after installing Firebase, I got new errors, that seem based on the library itself. Could that be that I need a specific version of the Firebase library? Unfortunately, I have no experience with Python...

```
# python3.9 launcher.py
Committing...
Running Setup...
fun
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/cogs/fun.py", line 5, in <module>
    from lib.bot.firebaseauth import addUser, getUser, getUserMail, updateMail, deleteUser
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/firebaseauth.py", line 1, in <module>
    from firebase import firebase
  File "/usr/local/lib/python3.9/dist-packages/firebase/__init__.py", line 3
    from .async import process_pool
          ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/temp/Chegg-Discord-BOT-main/launcher.py", line 5, in <module>
    bot.run(VERSION)
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 54, in run
    self.setup()
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 45, in setup
    self.load_extension(f"lib.cogs.{cog}")
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'lib.cogs.fun' raised an error: SyntaxError: invalid syntax (__init__.py, line 3)
```

Anyway, I'm trying to run it on Ubuntu 18.04

**Comment by woosal1337** [comment]
`pip install git+https://github.com/ozgur/python-firebase`

**Comment by SaSiNO97** [comment]
@woosal1337 Thank you very much for your help so far ♥

After removing the previous python-firebase and installing it from your repository, I still got issues with it:
(Ubuntu 18.04 Server)

```
# python3.9 launcher.py
Committing...
Running Setup...
fun
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/cogs/fun.py", line 5, in <module>
    from lib.bot.firebaseauth import addUser, getUser, getUserMail, updateMail, deleteUser
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/firebaseauth.py", line 3, in <module>
    firebase = firebase.FirebaseApplication('FIREBASELINK', None)
  File "/usr/local/lib/python3.9/dist-packages/firebase/firebase.py", line 229, in __init__
    assert dsn.startswith('https://'), 'DSN must be a secure URL'
AssertionError: DSN must be a secure URL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/temp/Chegg-Discord-BOT-main/launcher.py", line 5, in <module>
    bot.run(VERSION)
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 54, in run
    self.setup()
  File "/home/users/temp/Chegg-Discord-BOT-main/lib/bot/__init__.py", line 45, in setup
    self.load_extension(f"lib.cogs.{cog}")
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'lib.cogs.fun' raised an error: AssertionError: DSN must be a secure URL
```

**Comment by woosal1337** [comment]
It looks like a directory/path issue. I guess you are using Linux not Windows. Try to figure out the paths correctly.
